on:
  schedule:
  - cron: '0 * * * *'
  push:
name: Link Checker
jobs:
  linkchecker:
    name: linkchecker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: linkchecker
      uses: cam-barts/linkchecker-action@master